INSERT INTO tech_stack (tech_stack_id, job_field, tech_stack_name) VALUES
                                                                       (1, "DESIGNER", "Figma"),
                                                                       (2, "DESIGNER", "Adobe XD"),
                                                                       (3, "DESIGNER", "Sketch"),
                                                                       (4, "DESIGNER", "Adobe Photoshop"),
                                                                       (5, "DESIGNER", "Adobe Illustrator"),
                                                                       (6, "DESIGNER", "InVision"),
                                                                       (7, "DESIGNER", "Blender"),
                                                                       (8, "DESIGNER", "Cinema 4D"),
                                                                       (9, "DESIGNER", "Lottie"),

                                                                       (10, "FRONTEND", "HTML"),
                                                                       (11, "FRONTEND", "CSS"),
                                                                       (12, "FRONTEND", "JavaScript"),
                                                                       (13, "FRONTEND", "TypeScript"),
                                                                       (14, "FRONTEND", "React.js"),
                                                                       (15, "FRONTEND", "Angular.js"),
                                                                       (16, "FRONTEND", "Vue.js"),
                                                                       (17, "FRONTEND", "Svelte"),
                                                                       (18, "FRONTEND", "Sass"),
                                                                       (19, "FRONTEND", "Tailwind CSS"),

                                                                       (20, "BACKEND", "Java"),
                                                                       (21, "BACKEND", "Kotlin"),
                                                                       (22, "BACKEND", "Python"),
                                                                       (23, "BACKEND", "Ruby"),
                                                                       (24, "BACKEND", "PHP"),
                                                                       (25, "BACKEND", "Go"),
                                                                       (26, "BACKEND", "Node.js"),
                                                                       (27, "BACKEND", "Spring Boot"),
                                                                       (28, "BACKEND", "Django/Flask"),
                                                                       (29, "BACKEND", "Express.js"),
                                                                       (30, "BACKEND", "AWS"),
                                                                       (31, "BACKEND", "MySQL"),
                                                                       (32, "BACKEND", "PostgreSQL"),
                                                                       (33, "BACKEND", "MongoDB"),
                                                                       (34, "BACKEND", "Docker"),
                                                                       (35, "BACKEND", "Redis"),
                                                                       (36, "BACKEND", "Kubernetes"),
                                                                       (37, "BACKEND", "Nginx"),
                                                                       (38, "BACKEND", "Kafka"),

                                                                       (39, "APP", "Swift (iOS)"),
                                                                       (40, "APP", "Kotlin (Android)"),
                                                                       (41, "APP", "Dart (Flutter)"),
                                                                       (42, "APP", "SwiftUI (iOS)"),
                                                                       (43, "APP", "Jetpack Compose (Android)"),
                                                                       (44, "APP", "Flutter"),
                                                                       (45, "APP", "React Native"),

                                                                       (46, "PM", "Jira"),
                                                                       (47, "PM", "Trello"),
                                                                       (48, "PM", "Asana"),
                                                                       (49, "PM", "Scrum"),
                                                                       (50, "PM", "Kanban"),
                                                                       (51, "PM", "Notion");